      SUBROUTINE CHCK6I(N,JL,A)
C  Copyright (C) 2019 J. M. Hutson & C. R. Le Sueur
C  Distributed under the GNU General Public License, version 3
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C  THIS SUBROUTINE CHECKS THAT FOR ASYMMETRIC TOP FUNCTIONS, THE A
C  COEFFICIENTS FOR REPEATED SETS OF JI (=JL(1,...)) ARE ORTHOGONAL TO
C  EACH OTHER.
C
C  CHECK6 DOES A VERY SIMILAR JOB...
      DIMENSION JL(4,N),A(1)
      DATA EPS/7.D-6/

      WRITE(6,600)
  600 FORMAT(/' CHCK6I.  INPUT FUNCTIONS WILL BE CHECKED FOR ',
     &       'ORTHOGONALITY.')
      NERR=0
      DO 1000 I1=2,N
      DO 1000 I2=1,I1-1
C  SEE IF SAME J-VALUE
        IF (JL(1,I2).NE.JL(1,I1)) GOTO 1000

 1001   TOTAL=0.D0
        DO 1100 II=1,2*JL(1,I1)+1
 1100     TOTAL=TOTAL+A(JL(4,I1)+II)*A(JL(4,I2)+II)
        IF (ABS(TOTAL).LE.EPS) GOTO 1000
        WRITE(6,698) I1,I2,TOTAL
  698   FORMAT(/' ***** CHCK6I ERROR.  LEVEL',2I4,' ARE NOT ORTHOGONAL.'
     &         ,'  OVERLAP =',E12.4)
        NERR=NERR+1
 1000 CONTINUE

      IF (NERR.LE.0) RETURN
      WRITE(6,697) NERR
  697 FORMAT(/' *****'/'  ***** CHCK6I.  NUMBER OF ERRORS =',I4/
     1       '  ***** EXECUTION TERMINATING UNLESS CHCK6I MODIFIED'/
     2       '  *****')
      STOP
      END
