      DOUBLE PRECISION FUNCTION DRCALC(RSTART,RSTOP,KSTEP,NSTEP,POW)
      IMPLICIT NONE
C  Copyright (C) 2019 J. M. Hutson & C. R. Le Sueur
C  Distributed under the GNU General Public License, version 3

C  CR LeSueur Jan 2019
C
C  THIS FUNCTION CALCULATES THE NEXT STEP SIZE WHEN STEP BOUNDARIES
C  ARE EQUALLY SPACED IN R**(1-POW) (WHICH CORRESPONDS TO STEP SIZE
C  SCALING AS POW)
C
C  NOTE THAT, FOR POWINT=1, THIS REDUCES TO CONSTANT STEP SIZE
C       AND   FOR POWINT=0, THE ARITHMETIC SERIES CAN NOT BE USED.
C                           DRCALC IS INSTEAD EXPRESSED AS
C                           DR*RNOW/RSTART.
C
      DOUBLE PRECISION, INTENT(IN) :: RSTART, RSTOP, POW
      INTEGER,          INTENT(IN) :: KSTEP, NSTEP

      DOUBLE PRECISION :: POWINT, ZSTART, ZSTOP, DZ, RNOW, RLAST,
     1                    POWINV

      POWINT=1.D0-POW
      POWINV=1D0/POWINT

      IF (POWINT.NE.0.D0) THEN
        ZSTART=RSTART**POWINT
        ZSTOP=RSTOP**POWINT
        DZ=(ZSTOP-ZSTART)/DBLE(NSTEP)

        RNOW=(ZSTART+DBLE(KSTEP+1)*DZ)**POWINV
        RLAST=(ZSTART+DBLE(KSTEP)*DZ)**POWINV
        DRCALC=RNOW-RLAST
      ELSE
        DZ=RSTART*((RSTOP/RSTART)**1.D0/DBLE(NSTEP)-1.D0)
        DRCALC=DZ*(1.D0+DZ/RSTART)**KSTEP
      ENDIF

      RETURN
      END
