      SUBROUTINE DVFREE(UJ,UJP,UN,UNP,WRONS,L,N,WV,R,NB)
C  Copyright (C) 2018 J. M. Hutson & C. R. Le Sueur
C  Distributed under the GNU General Public License, version 3
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C  DOUBLE PRECISION ASYMPTOTIC FUNCTIONS FOR MATCHING TO S-MATRIX.
C
C  ON ENTRY: WV IS ARRAY DIMENSION (N) OF WEIGHTS;
C            L IS ARRAY OF ANGULAR MOMENTUM LABELS;
C            NB IS INDEX OF ENERGY ORDERING OF BASIS FUNCTIONS;
C            R IS DISTANCE.
C            ALL UNCHANGED ON EXIT.
C  ON EXIT:  UJ, UJP, UN AND UNP ARE REGULAR (J) AND IRREGULAR (N) BESSEL
C            FUNCTIONS AND DERIVATIVES (P);
C            WRONS IS WEIGHTED WRONSKIAN.
      DIMENSION UJ(N),UJP(N),UN(N),UNP(N),WRONS(N),WV(N)
      DIMENSION L(N),NB(N)

      DO 3000 I=1,N
        NX=NB(I)
        DW=WV(NX)
        DARG=DW*R
        CALL RBES(L(NX),DARG,UJ(NX),UJP(NX),UN(NX),UNP(NX))
        UJP(NX)=UJP(NX)*DW
        UNP(NX)=UNP(NX)*DW
 3000   WRONS(NX)=(UJ(NX)*UNP(NX)-UJP(NX)*UN(NX))/SQRT(DW)

      RETURN
      END
