      SUBROUTINE EFV9(INDSV)
C  Copyright (C) 2019 J. M. Hutson & C. R. Le Sueur
C  Distributed under the GNU General Public License, version 3
C
C  Written by CR Le Sueur 2017 ish
C  THIS IS A DUMMY COPY OF EFV9, USED IF A BESPOKE VERSION IS NOT
C  REQUIRED.  IT SHOULD NEVER ACTUALLY BE CALLED.
C
C  EFV9 IS CALLED IN TWO TYPES OF CIRCUMSTANCES
C  A) IF THE MAPPING BETWEEN THE EFVS AND SCALAR MULTIPLIERS OF THE
C     COUPLING MATRICES (ELEMENTS OF VCONST ARRAY) IS NOT ONE-TO-ONE
C  B) IF THE SINGLE VARYING QUANTITY USED TO SEARCH FOR FIELD-DEPENDENT
C     QUANTITIES (RESONANCES, BOUND STATES) IS NOT ONE OF THE EFVS
C
C  FOR CASE A) MAPEFV (SET IN BAS9IN) MUST BE LESS THAN 0 AND THIS
C  ROUTINE SHOULD INCLUDE CODE FOR THE VALUE SET.  IF THERE ARE
C  SEVERAL DIFFERENT POSSIBILITIES, THESE CAN BE COVERED BY INCLUDING
C  MAPEFV IN A NAMELIST READ IN BAS9IN, IN WHICH CASE THIS ROUTINE SHOULD
C  INCLUDE CODE FOR EACH ONE.
C
C  FOR CASE B) IFVARY(1) (READ IN FROM &INPUT NAMELIST) MUST BE LESS THAN
C  ZERO AND THIS ROUTINE SHOULD INCLUDE CODE FOR THE POSSIBLE CHOICES
C  OF VALUE.  IFVARY(1) IS PASSED TO EFV9 IN THE DUMMY VARIABLE INDSV.
C  THE CURRENT VALUE OF THIS DUMMY VARIABLE IS STORED IN EFV(NEFV+1)
      USE efvs
      IMPLICIT NONE

      INTEGER, INTENT(IN) :: INDSV

      IF (INDSV.LT.0) THEN
C  WRITE CODE TO CONSTRUCT EFV ARRAY FROM THE VALUE IN EFV(NEFV+1)
      ENDIF

      IF (MAPEFV.LT.0) THEN
C  WRITE CODE TO CONSTRUCT VCONST ARRAY FROM VALUES IN EFV ARRAY
      ENDIF

      WRITE(6,*) ' *** DUMMY VERSION OF EFV9 CALLED IN ERROR'
      STOP

      END
