      SUBROUTINE GCLOCK(XTIME)
C  Copyright (C) 2019 J. M. Hutson & C. R. Le Sueur
C  Distributed under the GNU General Public License, version 3
      DOUBLE PRECISION XTIME
      REAL TIME,TTIME
      DIMENSION TTIME(2)
C
C  THIS ROUTINE IS MACHINE-DEPENDENT.
C  IT SHOULD RETURN THE ELAPSED CPU TIME IN UNITS OF SECONDS.
C  ONLY DIFFERENCES ARE USED, SO IT NEED NOT BE AN ABSOLUTE VALUE.
C
C  DUMMY RESULT FOR VANILLA DISTRIBUTION
      XTIME=0.D0
C
C  CODE BELOW CALLS THE BSD UNIX TIMING ROUTINE.
C  A C VERSION OF etime FOR MOST OTHER UNIX SYSTEMS IS AVAILABLE FROM JM Hutson.
C     TIME=etime(TTIME)
C     XTIME=DBLE(TIME)
C
C  CODE BELOW IS THE GISS ROUTINE
C     CALL CLOCKS(ITIME)
C     XTIME=-ITIME
C     XTIME=XTIME*1.D-2

C  CODE BELOW CALLS THE F90 (AND ONWARDS) INTRINSIC cpu_time
      CALL cpu_time(XTIME)
      RETURN
      END
