      FUNCTION GSYMTP(J1,K1,J2,K2,MVAL,LM,MU)
C  Copyright (C) 2019 J. M. Hutson & C. R. Le Sueur
C  Distributed under the GNU General Public License, version 3
C
C  THIS FUNCTION CALCULATES THE COUPLING COEFFICIENT REQUIRED FOR
C  THE MCGUIRE-KOURI COUPLED STATES APPROXIMATION BETWEEN AN ATOM AND
C  A NON-LINEAR ROTOR (ITYP=5/6)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C  PIFCT IS 1/SQRT(4PI)
      DATA Z0/0.D0/, PIFCT/.282094791773878209D0/
C  INTERNAL FUNCTION
      Z(X)=2.D0*X+1.D0
C
      XJ1=J1
      XK1=K1
      XJ2=J2
      XK2=K2
      XM=MVAL
      XLM=LM
      XMU=MU
      GSYMTP=0.D0
      F=THRJ(XJ1,XLM,XJ2,XK1,XMU,-XK2)
      IF (ABS(F).LE.1.D-8) RETURN

      F=F*THRJ(XJ1,XLM,XJ2,-XM,Z0,XM)
      IF (ABS(F).LE.1.D-8) RETURN

      GSYMTP=F*PIFCT*SQRT(Z(XJ1)*Z(XJ2)*Z(XLM))*PARSGN(K1+MVAL)
      RETURN
      END
