      SUBROUTINE HRECUR(PN,DPN,PN1,X,NN)
C  Copyright (C) 2019 J. M. Hutson & C. R. Le Sueur
C  Distributed under the GNU General Public License, version 3
C
C  S Green: ADAPTED FROM STROUD AND SECREST, GAUSSIAN QUADRATURE FORMULAS.
C  THIS SUBROUTINE CALCULATES THE NN-TH HERMITE POLYNOMIAL AT POINT X
C  AND ITS DERIVATIVE
C
C  ON ENTRY: X CONTAINS POINT AT WHICH TO EVALUATE;
C            NN IS ORDER OF HERMITE POLYNOMIAL.
C            UNCHANGED ON EXIT.
C  ON EXIT:  PN CONTAINS VALUE OF NN-TH HERMITE POLYNOMIAL AT X;
C            DPN CONTAINS DERIVATIVE OF PN AT X;
C            PN1 CONTAINS VALUE OF NN-1-TH HERMITE POLYNOMIAL AT X.
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)

      P1=1.D0
      P=X
      DP1=0.D0
      DP=1.D0

      DO 1 J=2,NN
        FJ=J
        FJ2=(FJ-1.D0)/2.D0
        Q=X*P-FJ2*P1
        DQ=X*DP+P-FJ2*DP1
        P1=P
        P=Q
        DP1=DP
 1      DP=DQ

      PN=P
      DPN=DP
      PN1=P1
      RETURN
      END
