      SUBROUTINE IOSBIN(NLEVV,ITYPE,JSTATE,MXA,IASYMU,IPHIFL,IOSNGP)
C  Copyright (C) 2019 J. M. Hutson & C. R. Le Sueur
C  Distributed under the GNU General Public License, version 3
C
C  THIS DUMMY ROUTINE NEEDED BECAUSE BOUND/FIELD USE THE SAME BASE
C  SUBROUTINE AS MOLSCAT.
      DIMENSION JSTATE(1),IOSNGP(1)

      WRITE(6,601)
  601 FORMAT(/' *** ERROR. IOSBIN CALLED BUT NOT IMPLEMENTED'/
     1       ' IOS OPTIONS ARE NOT AVAILABLE IN THIS VERSION')
      STOP
      END
