      SUBROUTINE ISUTP(ISU,EN,JTL,JST,JT,NVC,NQL,QLS,QLT)
C  Copyright (C) 2019 J. M. Hutson & C. R. Le Sueur
C  Distributed under the GNU General Public License, version 3
C
C  THIS SUBROUTINE WRITES CROSS SECTIONS TO THE OUTPUT STREAM ISU
C
C  ON ENTRY: ISU IS THE LABEL FOR THE OUTPUT STREAM;
C            EN  IS AN ENERGY;
C            TJL IS THE STARTING VALUE FOR THE 'JTOT' LOOP;
C            JST IS THE STEP SIZE OF THE LOOP OVER JTOT;
C            JT  IS THE CURRENT VALUE OF JTOT;
C            QLS AND QLT ARE ARRAYS OF DIMENSION (NVC,NVC) AND
C            (NVC,NVC,NQL) RESPECTIVELY.
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION QLS(NVC,NVC),QLT(NVC,NVC,NQL)
      IF (ISU.LE.0) RETURN
      WRITE(ISU,3232) EN,JTL,JST,JT
 3232 FORMAT('  ENERGY',F10.3,'    JTOT',3I6)
      WRITE(ISU,3233) ((QLS(IV,IVP),IV=1,NVC),IVP=1,NVC)
 3233 FORMAT(1P,5E16.8)
      WRITE(ISU,3233) (((QLT(IV,IVP,L),IV=1,NVC),IVP=1,NVC),L=1,NQL)
      RETURN
      END
