C  Copyright (C) 2019 J. M. Hutson & C. R. Le Sueur
C  Distributed under the GNU General Public License, version 3
C
C  THIS ROUTINE IS THE MAIN PROGRAM FOR MOLSCAT (ETC) VERSION 2022 AND ONWARDS,
C  WITH DYNAMIC ARRAY ALLOCATION CAPABILITY.
C
C  CALL PRINCIPAL MOLSCAT/BOUND/FIELD DRIVER SUBROUTINE
C
      CALL DRIVER
      STOP
      END
