C  Copyright (C) 2019 J. M. Hutson & C. R. Le Sueur
C  Distributed under the GNU General Public License, version 3
C
C  THIS ROUTINE IS THE MAIN PROGRAM FOR MOLSCAT (ETC) VERSION 12 AND ONWARDS,
C  WITH DYNAMIC SPACE ALLOCATION CAPABILITY.
C
C  INCREASE MXDIM AS NECESSARY TO PROVIDE SUFFICIENT WORKSPACE.
C  IXNEXT,NIPR ARE INITIALIZED IN DRIVER
C
      PARAMETER (MXDIM=1000000)
      DOUBLE PRECISION X
      DIMENSION X(MXDIM)
      COMMON /MEMORY/ MX,IXNEXT,NIPR,IDUMMY,X
C
      MX=MXDIM
C
C  CALL PRINCIPAL MOLSCAT/BOUND/FIELD DRIVER SUBROUTINE
C
      CALL DRIVER
      STOP
      END
