      SUBROUTINE MAXMGV(A, NA, C, NC, N)
C  Copyright (C) 2019 J. M. Hutson & C. R. Le Sueur
C  Distributed under the GNU General Public License, version 3
C
C  SUBROUTINE TO SCAN A VECTOR FOR ITS MAXIMUM MAGNITUDE (ABSOLUTE
C  VALUE) ELEMENT
C  CURRENT REVISION DATE: 24-SEPT-87
C  -------------------------------------------------------------------
C  VARIABLES IN CALL LIST:
C  A:   FLOATING POINT INPUT VECTOR
C  NA:  INTEGER ELEMENT STEP FOR A
C  C:   FLOATING POINT OUTPUT SCALAR: ON RETURN CONTAINS VALUE OF
C       MAXIMUM MAGNITUDE (ABSOLUTE VALUE) ELEMENT
C  NC:  INTEGER INDEX OF MAXIMUM MAGNITUDE ELEMENT
C  N:   INTEGER ELEMENT COUNT
C  SUBROUTINES CALLED:
C  IDAMAX: BLAS ROUTINE TO FIND INDEX OF MAXIMUM MAGNITUDE (ABSOLUTE
C          VALUE) ELEMENT
C  -------------------------------------------------------------------
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDAMAX, N, NA, NC
      DIMENSION A(1)
      NC = ( IDAMAX(N, A, NA) - 1) * NA + 1
      C = ABS( A(NC) )
      RETURN
      END
