      SUBROUTINE ORDER(I,J)
C  Copyright (C) 2019 J. M. Hutson & C. R. Le Sueur
C  Distributed under the GNU General Public License, version 3
C
C  SUBROUTINE TO REARRANGE TWO FOURIER COMPONENTS INTO
C  A UNIQUELY DEFINED EQUIVALENT PAIR.
C
C  EQUIV  = .TRUE. IF THE TWO LATTICE VECTORS ARE EQUIVALENT
C  ORTHOG = .TRUE. IF THE LATTICE VECTORS ARE ORTHOGONAL
C  HEX    = .TRUE. IF LATTICE HAS HEXAGONAL SYMMETRY
C  CURRENTLY SET UP FOR HEXAGONAL LATTICE, AS IN H-Xe-C
C
      LOGICAL HEX, ORTHOG, EQUIV
      COMMON /LATSYM/ HEX,ORTHOG,EQUIV
C
    5 IF (.NOT.EQUIV .OR. ABS(I).GE.ABS(J)) GOTO 10

      K=I
      I=J
      J=K
   10 IF (I.GE.0) GOTO 20

      I=-I
      J=-J
   20 CONTINUE
      IF (ORTHOG) J=ABS(J)
      IF (.NOT.HEX .OR. J.LE.0) RETURN

      K=I
      I=J
      J=J-K
      GOTO 5
      END
