      SUBROUTINE REINIV(SCALAM)
C  Copyright (C) 2020 J. M. Hutson & C. R. Le Sueur
C  Distributed under the GNU General Public License, version 3
C
C  THIS IS A DUMMY VERSION OF REINIV
C  FOR CASES WHERE SCALAM IS NOT USED TO RESET A POTENTIAL PARAMETER
      IMPLICIT NONE
      DOUBLE PRECISION :: SCALAM
C
      RETURN
      END
