      SUBROUTINE SCAPOT(P,MXLAM,EP2RU)
      USE efvs, ONLY: SCALAM
C  Copyright (C) 2019 J. M. Hutson & C. R. Le Sueur
C  Distributed under the GNU General Public License, version 3
C
C  WRITTEN ON 26-10-2018 BY CRLS
C
C  THIS SUBROUTINE SCALES ALL THE POTENTIAL COEFFICIENTS P BY THE
C  SCALING FACTOR SCALAM, AND THEN USES EP2RU TO CONVERT THEM INTO
C  INTERNAL UNITS (THIS CODE WAS ORIGINALLY IN WAVMAT)
      IMPLICIT NONE

      INTEGER,          INTENT(IN)    :: MXLAM
      DOUBLE PRECISION, INTENT(IN)    :: EP2RU
      DOUBLE PRECISION, INTENT(INOUT) :: P(MXLAM)

      INTEGER I

      DO I=1,MXLAM
        P(I)=P(I)*SCALAM
        P(I)=P(I)*EP2RU
      ENDDO

      RETURN
      END
