      SUBROUTINE SGNCHK(A,B,N)
C  Copyright (C) 2019 J. M. Hutson & C. R. Le Sueur
C  Distributed under the GNU General Public License, version 3
C
C  ROUTINE TO CHANGE SIGN OF COLUMN OF B IF ELEMENT OF A, CORRESPONDING
C  TO BIGGEST ELEMENT IN THAT COLUMN OF B, IS NEGATIVE.
C
C  ON ENTRY: A, B ARE ARRAYS DIMENSIONED (N,N)
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION A(*),B(*)

      IND=-N
      DO I=1,N
        IND=IND+N
        VMAX=0.D0
        JMAX=0
C  FIND MAXIMUM VALUE OF B IN COLUMN I
        DO J=1,N
          IF (ABS(B(IND+J)).LT.VMAX) CYCLE
          JMAX=J
          VMAX=B(IND+JMAX)
        ENDDO
        IF (JMAX.EQ.0) GOTO 999
C  CHECK SIGN OF A FOR CORRESPONDING INDEX
        TEST=SIGN(B(IND+JMAX),A(IND+JMAX))
        IF (TEST.EQ.B(IND+JMAX)) CYCLE
C  IF NEGATIVE CHANGE SIGNS OF ELEMENTS IN COLUMN I OF B
        DO J=1,N
          B(IND+J)=-B(IND+J)
        ENDDO
      ENDDO
      RETURN

999   WRITE(6,100)
100   FORMAT(/10X,'JMAX EQ. 0 IN SGNCHK')
      RETURN
      END
