      module sizes
C  Copyright (C) 2020 J. M. Hutson & C. R. Le Sueur
C  Distributed under the GNU General Public License, version 3
      IMPLICIT NONE
C
C  HERE ARE STORED ARRAY DIMENSIONS FOR LARGE(ISH) ARRAYS IN DRIVER ROUTINES
      INTEGER, PARAMETER :: MXFLD_in_MOLSCAT=10000, MXFLD_in_BOUND=1000
      INTEGER, PARAMETER :: MXNRG_in_MOLSCAT=2000,  MXNRG_in_FIELD=100
      INTEGER, PARAMETER :: MXNODE=200 ! BOUND AND FIELD ONLY
      INTEGER, PARAMETER :: MXLN=200   ! MOLSCAT ONLY
C
C  HERE ARE STORED ARRAY DIMENSIONS FOR ARRAYS IN MODULES
C
C  BASIS_DATA (CMBASE AS WAS)
      INTEGER, PARAMETER :: MXJLVL=4000, MXELVL=1000
      INTEGER, PARAMETER :: MXROTS=12,   MXSYMS=10
C
C  POTENTIAL (VLUSE AS WAS)
      INTEGER, PARAMETER :: MXOMEG=20,   MXLMDA=2000
C
C  ANGLES
      INTEGER, PARAMETER :: MXANG=7
C
C  NUMBER OF FIELDS FOR RESONANCE-LOCATION ITERATIONS (NOT IN MODULE)
      INTEGER, PARAMETER :: MXLOC=20

      end module sizes
