      SUBROUTINE STRY(NLB,NUB,N,ITRY,EIGNEW)
C  Copyright (C) 2018 J. M. Hutson & C. R. Le Sueur
C  Distributed under the GNU General Public License, version 3
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      SAVE ITOLD
C
C  THIS TESTS TO SEE IF ALL THE OFF-DIAGONAL ELEMENTS OF THE
C  EIGENVECTORS HAVE BECOME NEGLIGIBLE COMPARED TO VTOL
C
      DIMENSION NLB(1),NUB(1)
      DIMENSION EIGNEW(1)
C  TOLERANCE TO DETERMINE DEGENERACY.
      DATA EPSIL / 1.D-2/
C  STORE OLD VALUE OF ITRY
      ITOLD = ITRY
      IF (N.LE.1) GOTO 15

      DO 10 I=1,N
C  TEST FOR DEGENERACY
        IF (I.EQ.1) GOTO 8
        DIFF = ABS(EIGNEW(I)-EIGNEW(I-1))
C  IF NEARLY DEGENERATE, DON'T BOTHER TO CHECK OFF-DIAGONAL
C  EIGENVECTOR COMPONENTS
        IF (DIFF.LT.EPSIL  ) GOTO 10
        IF (I.EQ.N) GOTO 9
8     DIFF = ABS(EIGNEW(I)-EIGNEW(I+1))
        IF (DIFF.LT.EPSIL  ) GOTO 10
9       IF (NLB(I).NE.NUB(I)) GOTO 20
10    CONTINUE

C  IF THE FOLLOWING STATEMENT IS REACHED, ALL COMPONENTS ARE
C  INDEED NEGLIGIBLE OR DEGENERATE
15    ITRY = 0
      GOTO 30

C  THIS IS REACHED WHEN AN ELEMENT IS TOO LARGE.
20    ITRY = -1
      RETURN

30    IF (ITOLD.EQ.0 .AND. ITRY.EQ.0) ITRY = 1
C  THIS MAKES SURE THAT THE ELEMENTS WERE ALSO NEGLIGIBLE AT THE
C  LAST STEP.
C  ITRY = 1 ON RETURN MEANS READY TO TRY FOR S-MATRIX CONVERGENCE
      RETURN
      END
