      SUBROUTINE THRLST(N,EINT,CENT,CM2RU,L,IBOUND,EFACT,UNAME)
C  Copyright (C) 2019 J. M. Hutson & C. R. Le Sueur
C  Distributed under the GNU General Public License, version 3
      IMPLICIT NONE

      INTEGER,          INTENT(IN) :: N,L(N),IBOUND
      DOUBLE PRECISION, INTENT(IN) :: EINT(N),CENT(N),CM2RU,EFACT
      CHARACTER(8),     INTENT(IN) :: UNAME

      INTEGER I

C  WRITE OUT THE ASYMPTOTIC THRESHOLDS
      IF (IBOUND.EQ.0) THEN
        WRITE(6,100) '    L ',TRIM(ADJUSTL(UNAME))
      ELSE
        WRITE(6,100) '<L**2>',TRIM(ADJUSTL(UNAME))
      ENDIF
  100 FORMAT(/1X,' THRESHOLDS CALCULATED FROM ASYMPTOTIC HAMILTONIAN:'
     1       //1X,' THRESHOLD',3X,A6,10X,'ENERGY/CM-1',16X,'ENERGY/',A)

      DO I=1,N
        IF (IBOUND.EQ.0) THEN
          WRITE(6,110) I,L(I),EINT(I)/CM2RU,EINT(I)/CM2RU/EFACT
        ELSE
          WRITE(6,120) I,CENT(I),EINT(I)/CM2RU,EINT(I)/CM2RU/EFACT
        ENDIF
      ENDDO
  110 FORMAT(5X,I6,2X,I6,  8X,1P,G19.12,8X,G19.12)
  120 FORMAT(5X,I6,2X,F6.2,8X,1P,G19.12,8X,G19.12)

      RETURN
      END
