      SUBROUTINE VRTP(IDERIV,R,V)
C  Copyright (C) 2019 J. M. Hutson & C. R. Le Sueur
C  Distributed under the GNU General Public License, version 3
      USE angles
C  THIS SUBROUTINE IS A WRAPPER FOR EXTPOT FUNCTION, USING 2 ANGLES IN
C  ITS ARGUMENTS
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C  CHANGED TO USE ANGLES MODULE ON 16-08-2018
C     COMMON/ANGLES/COSANG(MXANG),FACTOR,IHOMO,ICNSYM,IHOMO2,ICNSY2
      IF (IDERIV.NE.0) GOTO 100
      V=EXTPOT(R,COSANG(1),COSANG(2))
      RETURN
C
  100 IF (IDERIV.GT.0) THEN
        WRITE(6,601)
  601   FORMAT(' *** ERROR IN VRTP - POTENTIAL DERIVATIVES',
     1    ' NOT SUPPORTED BY THIS VERSION')
        STOP
      ENDIF
C
      IF (IDERIV.LT.-1) RETURN
      CALL EXTINT
      R=1.D0
      V=1.D0
      RETURN
      END
