      SUBROUTINE WAVEIG(W, EIGNOW, SCR1, SCR2, RNOW, NCH, P, MXLAM, VL,
     1                  IV, RMLMDA, ERED, EINT, CENT, NPOTL, IPRINT)
C  This subroutine is part of the MOLSCAT, BOUND and FIELD suite of programs
*  THIS SUBROUTINE FIRST SETS UP THE WAVEVECTOR MATRIX AT RNOW
*  THEN OBTAINS ITS EIGENVALUES
*  WRITTEN BY:  MILLARD ALEXANDER
*  CURRENT REVISION DATE: 25-SEPT-87
* ----------------------------------------------------------------
*  VARIABLES IN CALL LIST:
*  W:           MATRIX OF MAXIMUM ROW DIMENSION NCH USED TO STORE
*               WAVEVECTOR MATRIX
*  EIGNOW:      ON RETURN:  ARRAY CONTAINING EIGENVALUES OF WAVEVECTOR M
*  SCR1, SCR2:  SCRATCH VECTORS OF DIMENSION AT LEAST NCH
*  RNOW:        VALUE OF INTERPARTICLE SEPARATION AT WHICH WAVEVECTOR MA
*               IS TO BE EVALUATED
*  NCH:         NUMBER OF CHANNELS
*  SUBROUTINES CALLED:
*     WAVMAT:         DETERMINES WAVEVECTOR MATRIX
*     F02AAF:         NAG ROUTINE TO OBTAIN EIGENVALUES OF REAL,
*                     SYMMETRIC MATRIX
*     DSCAL, DCOPY:   LINPACK BLAS ROUTINES
* ----------------------------------------------------------------
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IERR, NCH, NCHM1, NCHP1
      EXTERNAL DSCAL, DCOPY, WAVMAT, F02AAF
*  SQUARE MATRIX (OF ROW DIMENSION NCH)
      DIMENSION W(1)
*  VECTORS DIMENSIONED AT LEAST NCH
      DIMENSION EIGNOW(1), SCR1(1), SCR2(1),P(1),VL(1),IV(1),EINT(1)
      DIMENSION CENT(1)
* ------------------------------------------------------------------
      DATA XMIN1 / -1.D0/
      NCHP1 = NCH + 1
      NCHM1 = NCH - 1
      CALL WAVMAT(W, NCH, RNOW, P, VL, IV, ERED, EINT, CENT, RMLMDA,
     1            SCR1, MXLAM, NPOTL, IPRINT)
C
*  SINCE WAVMAT RETURNS NEGATIVE OF LOWER TRIANGLE OF W(R) MATRIX (EQ.(3
*  M.H. ALEXANDER, "HYBRID QUANTUM SCATTERING ALGORITHMS ..."),
*  NEXT LINE CHANGES ITS SIGN
      CALL DSCAL(NCH*NCH, XMIN1, W, 1)
C
      IERR=0
      CALL F02AAF(W, NCH, NCH, EIGNOW, SCR1, IERR)
      IF (IERR.NE.0) THEN
        WRITE (6, 120) IERR
120     FORMAT('  *** F02AAF IERR =',I3,' .NE. 0 IN WAVEIG; ABORT ***')
        STOP
      ENDIF
C
      RETURN
      END
