      FUNCTION XNINEJ(IX1,IY1,IZ1,IX2,IY2,IZ2,IX3,IY3,IZ3)
C  Copyright (C) 2019 J. M. Hutson & C. R. Le Sueur
C  Distributed under the GNU General Public License, version 3
C
C  FUNCTION TO CALCULATE 9J (IX1 IY1 IZ1)
C                           (IX2 IY2 IZ2)
C                           (IX3 IY3 IZ3)
C  BY EXTRACTING VALUE CORRESPONDING TO IZ1 FROM ARRAY RETURNED BY
C  SUBROUTINE J9J
C
C  ON ENTRY: I[XYZ][123] ARE THE RELEVANT SPIN BASIS LABELS.
C  ALL VALUES UNCHANGED ON EXIT.
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION XJ9J(200)
      DATA MXDIM/200/
C
      IVAL=MXDIM
      CALL J9J(DBLE(IX1),DBLE(IY1),
     1         DBLE(IX2),DBLE(IY2),DBLE(IZ2),
     2         DBLE(IX3),DBLE(IY3),DBLE(IZ3),
     3         IVAL,Z1MIN,XJ9J)
      IND=1+IZ1-INT(Z1MIN+0.1D0)
      XNINEJ=0.D0
      IF (IND.GE.1 .AND. IND.LE.IVAL) XNINEJ=XJ9J(IND)
      RETURN
      END
